import type { Metadata } from "next";
import { Leaf, Target, Eye, Users } from "lucide-react";

export const metadata: Metadata = {
  title: "About",
  description: "Learn about FloraGuard's mission, team, and technology.",
};

export default function AboutPage() {
  return (
    <div className="py-16 sm:py-24">
      {/* Header */}
      <section className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 text-center mb-20">
        <div className="inline-flex items-center gap-2 rounded-full bg-flora-100 px-4 py-1.5 text-sm font-medium text-flora-700 mb-6">
          <Leaf className="h-3.5 w-3.5" aria-hidden="true" />
          Our Story
        </div>
        <h1 className="text-4xl sm:text-5xl font-bold text-gray-900">
          Protecting Crops with AI
        </h1>
        <p className="mt-6 text-lg text-gray-600 max-w-2xl mx-auto leading-relaxed">
          FloraGuard was born from a simple observation: most crop damage could be prevented if
          farmers had access to fast, accurate disease diagnosis. We built the tool we wished existed.
        </p>
      </section>

      {/* Mission / Vision / Values */}
      <section className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 mb-20">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {[
            {
              icon: Target,
              title: "Our Mission",
              body: "To democratize precision agriculture by putting AI-powered plant disease detection in every farmer's pocket.",
            },
            {
              icon: Eye,
              title: "Our Vision",
              body: "A world where no crop is lost to a preventable disease — where early detection becomes the norm, not the exception.",
            },
            {
              icon: Users,
              title: "Our Values",
              body: "Accuracy over speed. Farmer privacy above all. Actionable insights rather than jargon. Accessibility for smallholder farmers worldwide.",
            },
          ].map(({ icon: Icon, title, body }) => (
            <div key={title} className="rounded-2xl border border-gray-200 bg-white p-8 shadow-sm">
              <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-flora-100">
                <Icon className="h-6 w-6 text-flora-600" aria-hidden="true" />
              </div>
              <h2 className="mt-5 text-xl font-semibold text-gray-900">{title}</h2>
              <p className="mt-3 text-gray-500 leading-relaxed">{body}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Technology */}
      <section className="bg-flora-50 py-16 mb-20">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-bold text-gray-900 mb-6">Our Technology</h2>
          <div className="space-y-4 text-gray-600 leading-relaxed">
            <p>
              FloraGuard&apos;s core is a <strong>YOLOv4 object detection model</strong> with a
              MobileNetV2 backbone — a lightweight yet powerful architecture optimized for running
              inference on server hardware without sacrificing accuracy.
            </p>
            <p>
              Images are processed by our dedicated ML inference service. The model outputs
              disease labels, confidence scores, and precise bounding boxes showing exactly
              which parts of the plant are affected.
            </p>
            <p>
              Treatment recommendations are generated by <strong>Google Gemini</strong>, combining
              our model&apos;s detections with agronomic knowledge to produce actionable, plain-language
              guidance.
            </p>
          </div>

          <div className="mt-8 grid grid-cols-2 sm:grid-cols-4 gap-4">
            {["YOLOv4", "MobileNetV2", "FastAPI", "Gemini AI"].map((tech) => (
              <div
                key={tech}
                className="rounded-lg bg-white border border-gray-200 px-4 py-3 text-center text-sm font-medium text-gray-700"
              >
                {tech}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Disclaimer */}
      <section className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
        <div className="rounded-2xl border border-amber-200 bg-amber-50 p-6">
          <h3 className="font-semibold text-amber-800 mb-2">Important Disclaimer</h3>
          <p className="text-sm text-amber-700 leading-relaxed">
            FloraGuard&apos;s AI detections and recommendations are designed as decision-support tools,
            not replacements for professional agronomic advice. Always consult a certified
            plant pathologist or agronomist before applying treatments, especially for large-scale
            or commercially significant crops.
          </p>
        </div>
      </section>
    </div>
  );
}
